site_name: Razor CSS docs
site_description: 'Razor CSS docs'
site_author: 'Razor CSS'
docs_dir: docs/
repo_name: 'Razor-Css/Documentaion'
repo_url: 'https://github.com/Razor-Css/Documentaion/'
nav:
    - Home: index.md
theme:
  name: 'windmill-dark'
